name: TweakCart2Intersections
main: net.tweakcraft.tweakcart2intersections.TweakCartIntersections
authors: [windwarrior, Edoxile]
website: https://github.com/TweakCraft/TweakCart2Plugins
version: 0.1
